# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OroshiX
tagline: 'Personal site'
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is where I will put my CV, experiences, and blog posts...
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oroshix.github.io" # the base hostname & protocol for your site, e.g. http://example.com
my_url: "https://oroshix.github.io"
twitter_username: Oroshi_X
github_username:  OroshiX
github: [metadata]
# Build settings
markdown: kramdown
#theme: jekyll-theme-architect
version: 0
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-mermaid
#mermaid:
#  src: '/js/mermaid.min.js'
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: "/blog/page:num/"
permalink:           pretty
sass:
  style: compressed
  sass_dir: _scss

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Projects:
    - '/projects'
  Scores:
    - '/scores'
  Wiki:
    - '/#'
    - { Flutter: '/flutter' }
    - { Android: '/android-summary' }
  Github Project:
    - 'https://github.com/OroshiX/OroshiX.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
collections:
  scores:
    output: true

disqus_short_name: 'oroshix' # leave blank if you don't want disqus

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
